---
- name: Copy and apply YAML files to master machine
  hosts: master
  tasks:
    - name: Copy YAML files from local machine to master machine
      copy:
        src: "front.yaml"
        dest: "/home/master/front.yaml"

    - name: Apply YAML files on master machine
      command: kubectl apply -f "/home/master/front.yaml"
