apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-dep
spec:
  selector:
    matchLabels:
      app: front-dep
  replicas: 2
  template:
    metadata:
      labels:
        app: front-dep
    spec:
      containers:
        - name: front-dep
          image: chedysk/front
          ports:
            - containerPort: 4200

---
# Service definition to expose the frontend deployment with NodePort
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: front-dep
spec:
  type: NodePort
  selector:
    app: front-dep
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30001
